/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms. */

var fibonacciSum = 0;
var fibonacci = [];
var num1 = 1;
var num2 = 2;
var limit = 100;

var populateFibonacci = function(num1, num2, limit) {
  fibonacci.push(num1);
  fibonacci.push(num2);
  var newNum = num1 + num2;

  while (newNum<=limit) {
    fibonacci.push(newNum);
    num1 = num2;
    num2 = newNum;
    newNum = num1 + num2;
  }

  return fibonacci;
};

var addEvens = function(array){
  var evensSum = 0;
  for (var i = 0; i < array.length; i++){
    if (array[i] % 2 === 0){
      evensSum += array[i];
    }
  }
  return evensSum;
};

console.log(populateFibonacci(1, 1, 1000));
console.log(addEvens(fibonacci));
